name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-ft
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Run ruff
        uses: chartboost/ruff-action@v1
        with:
          version: 0.0.270
      - name: Run black
        uses: psf/black@stable
        with:
          version: 23.3.0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          version: v0.7.0
